All properties from properties.json included in the package.json
adobe/aem-site-template-basic pull request #3
Opened 2020-11-09 06:58 UTC by bartoszglow

All properties from properties.json included in the package.json

## Description

AEM Site Template properties which are used by the Site Wizard are now moved from the `properties.json` and included in the `pakcage.json` to not duplicated some of them.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2020-11-09 10:12 UTC, basecode approved these changes
One comment, otherwise good!

2020-11-09 10:12 UTC, basecode commented on package.json
> +  "site_template": {
Looking [at the spec](https://docs.npmjs.com/cli/v6/configuring-npm/package-json) and seeing the usage of camel case like `devDependencies `, I would propose to rename to `siteTemplate` for consistency reasons.

2020-11-09 10:14 UTC, basecode reviewed
just for the record :) missing task: update dependency to template builder pkg

2020-11-09 10:49 UTC, jckautzmann commented on package.json
> +    "sourceRepositoryUrl": "https://github.com/adobe/aem-sites-template-basic"
typo in the URL: sites -> site

2020-11-09 15:15 UTC, bartoszglow commented
Waiting for #1 to be merged in first. Then we can release new patch version of AEM-site-template-builder and update this PR with proper npm dependency.

2020-11-09 18:05 UTC, basecode requested changes

2020-11-09 18:05 UTC, basecode commented on package.json
> +    "createdBy": "Adobe",
`title` got lost.

2020-11-10 08:59 UTC, basecode approved these changes

2020-11-10 10:21 UTC, merged